version: '3'
services:
  web:
    build: .
    ports:
      - '${APP_PORT:-8000}:8000'
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '${DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-db}
      MYSQL_USER: ${DB_USERNAME:-django}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      TZ: 'Asia/Tokyo'
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data: