# Generated by Django 4.1.5 on 2023-01-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careers_text', models.TextField()),
                ('hobbies', models.TextField()),
                ('careers_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.careerslist')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.skills')),
            ],
        ),
    ]
