# Generated by Django 4.1.5 on 2023-01-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_careerslist_profile_alter_skills_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='comment',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='prof.study')),
            ],
        ),
    ]
