# Generated by Django 4.1.5 on 2023-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_remove_study_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateField(),
        ),
    ]
