# Generated by Django 4.1.5 on 2023-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_alter_comments_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(default='千葉県', max_length=10),
            preserve_default=False,
        ),
    ]
