# Generated by Django 4.1.5 on 2023-01-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_profile_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(max_length=20),
        ),
    ]
