# Generated by Django 4.1.5 on 2023-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_alter_profile_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
